// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import { t as __t, } from "spacetimedb";
export default __t.row({
    id: __t.u64().primaryKey(),
    sessionId: __t.u64().name("session_id"),
    idempotencyKey: __t.string().name("idempotency_key"),
    source: __t.string(),
    title: __t.string(),
    content: __t.string(),
    url: __t.option(__t.string()),
    createdAt: __t.timestamp().name("created_at"),
});
