// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).
/* eslint-disable */
/* tslint:disable */
import { DbConnectionBuilder as __DbConnectionBuilder, DbConnectionImpl as __DbConnectionImpl, SubscriptionBuilderImpl as __SubscriptionBuilderImpl, convertToAccessorMap as __convertToAccessorMap, makeQueryBuilder as __makeQueryBuilder, procedures as __procedures, reducerSchema as __reducerSchema, reducers as __reducers, schema as __schema, table as __table, } from "spacetimedb";
// Import all reducer arg schemas
import AdvanceMessageStatusReducer from "./advance_message_status_reducer.js";
import CreateSessionReducer from "./create_session_reducer.js";
import FailSessionReducer from "./fail_session_reducer.js";
import FinalizeVerdictReducer from "./finalize_verdict_reducer.js";
import IngestEvidenceReducer from "./ingest_evidence_reducer.js";
import MarkAnalyzingReducer from "./mark_analyzing_reducer.js";
import PostArgumentReducer from "./post_argument_reducer.js";
import RecordFallacyAlertReducer from "./record_fallacy_alert_reducer.js";
import StartDebateReducer from "./start_debate_reducer.js";
// Import all procedure arg schemas
// Import all table schema definitions
import AlertRow from "./alert_table.js";
import EvidenceRow from "./evidence_table.js";
import JurySessionRow from "./jury_session_table.js";
import MessageRow from "./message_table.js";
import VerdictRow from "./verdict_table.js";
/** Type-only namespace exports for generated type groups. */
/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
    alert: __table({
        name: 'alert',
        indexes: [
            { accessor: 'id', name: 'alert_id_idx_btree', algorithm: 'btree', columns: [
                    'id',
                ] },
            { accessor: 'alert_session_id', name: 'alert_session_id_idx_btree', algorithm: 'btree', columns: [
                    'sessionId',
                ] },
        ],
        constraints: [
            { name: 'alert_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, AlertRow),
    evidence: __table({
        name: 'evidence',
        indexes: [
            { accessor: 'id', name: 'evidence_id_idx_btree', algorithm: 'btree', columns: [
                    'id',
                ] },
            { accessor: 'evidence_idempotency_key', name: 'evidence_idempotency_key_idx_btree', algorithm: 'btree', columns: [
                    'idempotencyKey',
                ] },
            { accessor: 'evidence_session_id', name: 'evidence_session_id_idx_btree', algorithm: 'btree', columns: [
                    'sessionId',
                ] },
        ],
        constraints: [
            { name: 'evidence_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, EvidenceRow),
    jurySession: __table({
        name: 'jury_session',
        indexes: [
            { accessor: 'jury_session_current_turn', name: 'jury_session_current_turn_idx_btree', algorithm: 'btree', columns: [
                    'currentTurn',
                ] },
            { accessor: 'jury_session_evidence_snapshot_id', name: 'jury_session_evidence_snapshot_id_idx_btree', algorithm: 'btree', columns: [
                    'evidenceSnapshotId',
                ] },
            { accessor: 'id', name: 'jury_session_id_idx_btree', algorithm: 'btree', columns: [
                    'id',
                ] },
            { accessor: 'jury_session_status', name: 'jury_session_status_idx_btree', algorithm: 'btree', columns: [
                    'status',
                ] },
        ],
        constraints: [
            { name: 'jury_session_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, JurySessionRow),
    message: __table({
        name: 'message',
        indexes: [
            { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
                    'id',
                ] },
            { accessor: 'message_idempotency_key', name: 'message_idempotency_key_idx_btree', algorithm: 'btree', columns: [
                    'idempotencyKey',
                ] },
            { accessor: 'message_status', name: 'message_message_status_idx_btree', algorithm: 'btree', columns: [
                    'messageStatus',
                ] },
            { accessor: 'message_role', name: 'message_role_idx_btree', algorithm: 'btree', columns: [
                    'role',
                ] },
            { accessor: 'message_session_id', name: 'message_session_id_idx_btree', algorithm: 'btree', columns: [
                    'sessionId',
                ] },
        ],
        constraints: [
            { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, MessageRow),
    verdict: __table({
        name: 'verdict',
        indexes: [
            { accessor: 'id', name: 'verdict_id_idx_btree', algorithm: 'btree', columns: [
                    'id',
                ] },
            { accessor: 'verdict_idempotency_key', name: 'verdict_idempotency_key_idx_btree', algorithm: 'btree', columns: [
                    'idempotencyKey',
                ] },
            { accessor: 'verdict_session_id', name: 'verdict_session_id_idx_btree', algorithm: 'btree', columns: [
                    'sessionId',
                ] },
        ],
        constraints: [
            { name: 'verdict_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, VerdictRow),
});
/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(__reducerSchema("advance_message_status", AdvanceMessageStatusReducer), __reducerSchema("create_session", CreateSessionReducer), __reducerSchema("fail_session", FailSessionReducer), __reducerSchema("finalize_verdict", FinalizeVerdictReducer), __reducerSchema("ingest_evidence", IngestEvidenceReducer), __reducerSchema("mark_analyzing", MarkAnalyzingReducer), __reducerSchema("post_argument", PostArgumentReducer), __reducerSchema("record_fallacy_alert", RecordFallacyAlertReducer), __reducerSchema("start_debate", StartDebateReducer));
/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures();
/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
    versionInfo: {
        cliVersion: "2.1.0",
    },
    tables: tablesSchema.schemaType.tables,
    reducers: reducersSchema.reducersType.reducers,
    ...proceduresSchema,
};
/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables = __makeQueryBuilder(tablesSchema.schemaType);
/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);
/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl {
}
/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder {
}
/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl {
    /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
    static builder = () => {
        return new DbConnectionBuilder(REMOTE_MODULE, (config) => new DbConnection(config));
    };
    /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
    subscriptionBuilder = () => {
        return new SubscriptionBuilder(this);
    };
}
