// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import { t as __t, } from "spacetimedb";
export default {
    sessionId: __t.u64(),
    idempotencyKey: __t.string(),
    source: __t.string(),
    title: __t.string(),
    content: __t.string(),
    url: __t.option(__t.string()),
};
