// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import { t as __t, } from "spacetimedb";
export default __t.row({
    id: __t.u64().primaryKey(),
    topic: __t.string(),
    status: __t.string(),
    currentTurn: __t.string().name("current_turn"),
    roundNumber: __t.u64().name("round_number"),
    maxRounds: __t.u64().name("max_rounds"),
    createdBy: __t.identity().name("created_by"),
    evidenceSnapshotId: __t.option(__t.u64()).name("evidence_snapshot_id"),
    createdAt: __t.timestamp().name("created_at"),
    updatedAt: __t.timestamp().name("updated_at"),
    verdictId: __t.option(__t.u64()).name("verdict_id"),
});
