// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  sessionId: __t.u64(),
  messageId: __t.option(__t.u64()),
  source: __t.string(),
  severity: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type Alert = __Infer<typeof Alert>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  sessionId: __t.u64(),
  source: __t.string(),
  title: __t.string(),
  content: __t.string(),
  url: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Evidence = __Infer<typeof Evidence>;

export const JurySession = __t.object("JurySession", {
  id: __t.u64(),
  topic: __t.string(),
  status: __t.string(),
  currentTurn: __t.string(),
  roundNumber: __t.u64(),
  maxRounds: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  verdictId: __t.option(__t.u64()),
});
export type JurySession = __Infer<typeof JurySession>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  sessionId: __t.u64(),
  role: __t.string(),
  sender: __t.identity(),
  content: __t.string(),
  roundNumber: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Verdict = __t.object("Verdict", {
  id: __t.u64(),
  sessionId: __t.u64(),
  decision: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type Verdict = __Infer<typeof Verdict>;

